// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_xmuyTsbpzNaa81s4OffSR4iBHxFM4zs',
    appId: '1:881824867457:web:121eeb4596919f82f9d980',
    messagingSenderId: '881824867457',
    projectId: 'socialapp-d99d3',
    authDomain: 'socialapp-d99d3.firebaseapp.com',
    storageBucket: 'socialapp-d99d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnfZBuMvHvZw4NN0QdJS4BchP9dZGc54A',
    appId: '1:881824867457:android:229b2cc6ef4b28c5f9d980',
    messagingSenderId: '881824867457',
    projectId: 'socialapp-d99d3',
    storageBucket: 'socialapp-d99d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA56-yE6MtQwuutZr7UxW2XCic7kl1fzII',
    appId: '1:881824867457:ios:8f82a766d87b3068f9d980',
    messagingSenderId: '881824867457',
    projectId: 'socialapp-d99d3',
    storageBucket: 'socialapp-d99d3.firebasestorage.app',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA56-yE6MtQwuutZr7UxW2XCic7kl1fzII',
    appId: '1:881824867457:ios:8f82a766d87b3068f9d980',
    messagingSenderId: '881824867457',
    projectId: 'socialapp-d99d3',
    storageBucket: 'socialapp-d99d3.firebasestorage.app',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_xmuyTsbpzNaa81s4OffSR4iBHxFM4zs',
    appId: '1:881824867457:web:d03f329ced45ecfff9d980',
    messagingSenderId: '881824867457',
    projectId: 'socialapp-d99d3',
    authDomain: 'socialapp-d99d3.firebaseapp.com',
    storageBucket: 'socialapp-d99d3.firebasestorage.app',
  );
}
